# Generated by Django 2.2.7 on 2019-12-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_registrohoraextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='compensar',
            field=models.BooleanField(default=False),
        ),
    ]
